### ISSUE TITLE
analysis time grow significantly after shipping vulture as a package

### ISSUE THREAD

**Issue by roivanov** [jendrikseipp/vulture#73]
vulture analysis for our project (80k lines) took about 6 seconds _before_ revision 7e41b08cbc7ef3a4076ee84c749a9a8058ed6e0c (Ship vulture as a package. (#54))
Please see attached 1.log

[1.zip](https://github.com/jendrikseipp/vulture/files/1156925/1.zip)

Since after that revision (and for all releases 0.15-0.18) analysis takes 1 hour.
Please see attached 2.log

Truss shows significantly increased amount of failed lstat64() and open64() system calls. See truss.out
Possible cause is **file vulture.py (for module vulture) not found** in "pip install" command.

[truss1-head.out.gz](https://github.com/jendrikseipp/vulture/files/1156937/truss1-head.out.gz)

591.550383    lstat64("/usr", 0xF8296830)                       = 0
591.550479    lstat64("/usr/lib", 0xF8296830)                   = 0
591.550545    lstat64("/usr/lib/python2.7", 0xF8296830) = 0
591.550630    lstat64("/usr/lib/python2.7/lib-tk", 0xF8296830) = 0
591.550730    stat64("/usr/lib/python2.7/lib-tk/vulture", 0xF8296C30) Err#2 ENOENT
591.550802    open64("/usr/lib/python2.7/lib-tk/vulture.so", O_RDONLY) Err#2 ENOENT
591.550850    open64("/usr/lib/python2.7/lib-tk/vulturemodule.so", O_RDONLY) Err#2 ENOENT
591.550926    open64("/usr/lib/python2.7/lib-tk/vulture.py", O_RDONLY) Err#2 ENOENT
591.550982    open64("/usr/lib/python2.7/lib-tk/vulture.pyc", O_RDONLY) Err#2 ENOENT
591.551094    lstat64("/tmp", 0xF8296830)                       = 0
591.551167    lstat64("/tmp/vulture-test", 0xF8296830)  = 0
591.551263    lstat64("/tmp/vulture-test/latest", 0xF8296830)   = 0
591.551362    lstat64("/tmp/vulture-test/latest/current", 0xF8296830) = 0
591.551433    lstat64("/tmp/vulture-test/latest/current/virt", 0xF8296830) = 0
591.551536    lstat64("/tmp/vulture-test/latest/current/virt/lib", 0xF8296830) = 0
591.551665    lstat64("/tmp/vulture-test/latest/current/virt/lib/python2.7", 0xF8296830) = 0
591.551796    lstat64("/tmp/vulture-test/latest/current/virt/lib/python2.7/site-packages", 0xF8296830) = 0
591.551939    stat64("/tmp/vulture-test/latest/current/virt/lib/python2.7/site-packages/vulture", 0xF8296C30) = 0
591.551997    stat64("/tmp/vulture-test/latest/current/virt/lib/python2.7/site-packages/vulture/__init__.py", 0xF82966E0) = 0
591.552122    open64("/tmp/vulture-test/latest/current/virt/lib/python2.7/site-packages/vulture/whitelists/django.py", O_RDONLY) Err#2 ENOENT
591.552252    lstat64("/tmp", 0xF8296830)                       = 0
591.552326    lstat64("/tmp/vulture-test", 0xF8296830)  = 0
591.552396    lstat64("/tmp/vulture-test/latest", 0xF8296830)   = 0
591.552467    lstat64("/tmp/vulture-test/latest/current", 0xF8296830) = 0
591.552538    lstat64("/tmp/vulture-test/latest/current/virt", 0xF8296830) = 0
591.552635    lstat64("/tmp/vulture-test/latest/current/virt/bin", 0xF8296830) = 0
591.552754    stat64("/tmp/vulture-test/latest/current/virt/bin/vulture", 0xF8296C30) = 0
591.552836    open64("/tmp/vulture-test/latest/current/virt/bin/vulture.so", O_RDONLY) Err#2 ENOENT
591.552903    open64("/tmp/vulture-test/latest/current/virt/bin/vulturemodule.so", O_RDONLY) Err#2 ENOENT
591.552958    open64("/tmp/vulture-test/latest/current/virt/bin/vulture.py", O_RDONLY) Err#2 ENOENT
591.553049    open64("/tmp/vulture-test/latest/current/virt/bin/vulture.pyc", O_RDONLY) Err#2 ENOENT
591.553162    lstat64("/tmp", 0xF8296830)                       = 0
591.553240    lstat64("/tmp/vulture-test", 0xF8296830)  = 0
591.553331    lstat64("/tmp/vulture-test/latest", 0xF8296830)   = 0
591.553400    lstat64("/tmp/vulture-test/latest/current", 0xF8296830) = 0
591.553506    lstat64("/tmp/vulture-test/latest/current/virt", 0xF8296830) = 0
591.553579    lstat64("/tmp/vulture-test/latest/current/virt/lib", 0xF8296830) = 0
591.553682    lstat64("/tmp/vulture-test/latest/current/virt/lib/python2.7", 0xF8296830) = 0
591.553799    stat64("/tmp/vulture-test/latest/current/virt/lib/python2.7/vulture", 0xF8296C30) Err#2 ENOENT
591.553860    open64("/tmp/vulture-test/latest/current/virt/lib/python2.7/vulture.so", O_RDONLY) Err#2 ENOENT
591.553954    open64("/tmp/vulture-test/latest/current/virt/lib/python2.7/vulturemodule.so", O_RDONLY) Err#2 ENOENT
591.554020    open64("/tmp/vulture-test/latest/current/virt/lib/python2.7/vulture.py", O_RDONLY) Err#2 ENOENT
591.554099    open64("/tmp/vulture-test/latest/current/virt/lib/python2.7/vulture.pyc", O_RDONLY) Err#2 ENOENT
591.554194    lstat64("/tmp", 0xF8296830)                       = 0
591.554286    lstat64("/tmp/vulture-test", 0xF8296830)  = 0
591.554386    lstat64("/tmp/vulture-test/latest", 0xF8296830)   = 0
591.554467    lstat64("/tmp/vulture-test/latest/current", 0xF8296830) = 0
591.554563    lstat64("/tmp/vulture-test/latest/current/virt", 0xF8296830) = 0
591.554668    lstat64("/tmp/vulture-test/latest/current/virt/lib", 0xF8296830) = 0
591.554752    lstat64("/tmp/vulture-test/latest/current/virt/lib/python2.7", 0xF8296830) = 0
591.554847    lstat64("/tmp/vulture-test/latest/current/virt/lib/python2.7/lib-dynload", 0xF8296830) = 0
591.554928    readlink("/tmp/vulture-test/latest/current/virt/lib/python2.7/lib-dynload", "/usr/lib/python2.7/lib-dynload", 1024) = 30
591.555026    lstat64("/usr", 0xF82966B0)                       = 0
591.555128    lstat64("/usr/lib", 0xF82966B0)                   = 0
591.555235    lstat64("/usr/lib/python2.7", 0xF82966B0) = 0
591.555300    lstat64("/usr/lib/python2.7/lib-dynload", 0xF82966B0) = 0
591.555408    stat64("/usr/lib/python2.7/lib-dynload/vulture", 0xF8296C30) Err#2 ENOENT
591.555468    open64("/usr/lib/python2.7/lib-dynload/vulture.so", O_RDONLY) Err#2 ENOENT
591.555543    open64("/usr/lib/python2.7/lib-dynload/vulturemodule.so", O_RDONLY) Err#2 ENOENT
591.555615    open64("/usr/lib/python2.7/lib-dynload/vulture.py", O_RDONLY) Err#2 ENOENT
591.555689    open64("/usr/lib/python2.7/lib-dynload/vulture.pyc", O_RDONLY) Err#2 ENOENT
591.555776    lstat64("/usr", 0xF8296830)                       = 0
591.555861    lstat64("/usr/lib", 0xF8296830)                   = 0
591.555957    lstat64("/usr/lib/python2.7", 0xF8296830) = 0
591.556046    stat64("/usr/lib/python2.7/vulture", 0xF8296C30) Err#2 ENOENT
591.556098    open64("/usr/lib/python2.7/vulture.so", O_RDONLY) Err#2 ENOENT
591.556145    open64("/usr/lib/python2.7/vulturemodule.so", O_RDONLY) Err#2 ENOENT
591.556192    open64("/usr/lib/python2.7/vulture.py", O_RDONLY) Err#2 ENOENT
591.556238    open64("/usr/lib/python2.7/vulture.pyc", O_RDONLY) Err#2 ENOENT
591.556320    lstat64("/usr", 0xF8296830)                       = 0
591.556387    lstat64("/usr/lib", 0xF8296830)                   = 0
591.556453    lstat64("/usr/lib/python2.7", 0xF8296830) = 0
591.556520    lstat64("/usr/lib/python2.7/plat-sunos5", 0xF8296830) = 0
591.556598    stat64("/usr/lib/python2.7/plat-sunos5/vulture", 0xF8296C30) Err#2 ENOENT
591.556650    open64("/usr/lib/python2.7/plat-sunos5/vulture.so", O_RDONLY) Err#2 ENOENT
591.556700    open64("/usr/lib/python2.7/plat-sunos5/vulturemodule.so", O_RDONLY) Err#2 ENOENT
591.556751    open64("/usr/lib/python2.7/plat-sunos5/vulture.py", O_RDONLY) Err#2 ENOENT
591.556826    open64("/usr/lib/python2.7/plat-sunos5/vulture.pyc", O_RDONLY) Err#2 ENOENT

**Comment by jendrikseipp** [comment]
Thanks for the detailed report! I just pushed 802ab4842483f02a10433635801e0a6247dc068c, which removes the **file vulture.py (for module vulture) not found** output. Does this change decrease the runtime again?

**Comment by roivanov** [comment]
Yes, this message is gone. Unfortunately runtime still huge. Truss still shows python trying to get lstat64/open64 of vulture* files again and again. Seems like some files not get cached. My guess 'python import something' should keep imported module in memory and not try loading it again.

6.650877    lstat64("/tmp", 0xF8B14F30)                        = 0
 6.650925    lstat64("/tmp/vulture-test", 0xF8B14F30)   = 0
 6.650972    lstat64("/tmp/vulture-test/latest", 0xF8B14F30)    = 0
 6.651029    lstat64("/tmp/vulture-test/latest/current", 0xF8B14F30) = 0
 6.651078    lstat64("/tmp/vulture-test/latest/current/virt", 0xF8B14F30) = 0
 6.651126    lstat64("/tmp/vulture-test/latest/current/virt/lib", 0xF8B14F30) = 0
 6.651173    lstat64("/tmp/vulture-test/latest/current/virt/lib/python2.7", 0xF8B14F30) = 0
 6.651260    lstat64("/tmp/vulture-test/latest/current/virt/lib/python2.7/site-packages", 0xF8B14F30) = 0
 6.651338    stat64("/tmp/vulture-test/latest/current/virt/lib/python2.7/site-packages/vulture", 0xF8B15330) = 0
 6.651381    stat64("/tmp/vulture-test/latest/current/virt/lib/python2.7/site-packages/vulture/__init__.py", 0xF8B14DE0) = 0
 6.651465    open64("/tmp/vulture-test/latest/current/virt/lib/python2.7/site-packages/vulture/whitelists/Whitelist.py", O_RDONLY) Err#2 ENOENT
 6.651555    lstat64("/tmp", 0xF8B14F30)                        = 0
 6.651605    lstat64("/tmp/vulture-test", 0xF8B14F30)   = 0
 6.651652    lstat64("/tmp/vulture-test/latest", 0xF8B14F30)    = 0
 6.651699    lstat64("/tmp/vulture-test/latest/current", 0xF8B14F30) = 0
 6.651748    lstat64("/tmp/vulture-test/latest/current/virt", 0xF8B14F30) = 0
 6.651803    lstat64("/tmp/vulture-test/latest/current/virt/bin", 0xF8B14F30) = 0
 6.651869    stat64("/tmp/vulture-test/latest/current/virt/bin/vulture", 0xF8B15330) = 0
 6.651912    open64("/tmp/vulture-test/latest/current/virt/bin/vulture.so", O_RDONLY) Err#2 ENOENT
 6.651954    open64("/tmp/vulture-test/latest/current/virt/bin/vulturemodule.so", O_RDONLY) Err#2 ENOENT
 6.651996    open64("/tmp/vulture-test/latest/current/virt/bin/vulture.py", O_RDONLY) Err#2 ENOENT
 6.652038    open64("/tmp/vulture-test/latest/current/virt/bin/vulture.pyc", O_RDONLY) Err#2 ENOENT
 6.652102    lstat64("/tmp", 0xF8B14F30)                        = 0
 6.652150    lstat64("/tmp/vulture-test", 0xF8B14F30)   = 0
 6.652199    lstat64("/tmp/vulture-test/latest", 0xF8B14F30)    = 0
 6.652246    lstat64("/tmp/vulture-test/latest/current", 0xF8B14F30) = 0
 6.652294    lstat64("/tmp/vulture-test/latest/current/onsite", 0xF8B14F30) = 0
 6.652357    stat64("/tmp/vulture-test/latest/current/onsite/vulture", 0xF8B15330) Err#2 ENOENT
 6.652401    open64("/tmp/vulture-test/latest/current/onsite/vulture.so", O_RDONLY) Err#2 ENOENT
 6.652443    open64("/tmp/vulture-test/latest/current/onsite/vulturemodule.so", O_RDONLY) Err#2 ENOENT
 6.652484    open64("/tmp/vulture-test/latest/current/onsite/vulture.py", O_RDONLY) Err#2 ENOENT
 6.652524    open64("/tmp/vulture-test/latest/current/onsite/vulture.pyc", O_RDONLY) Err#2 ENOENT
 6.652590    lstat64("/tmp", 0xF8B14F30)                        = 0
 6.652638    lstat64("/tmp/vulture-test", 0xF8B14F30)   = 0
 6.652685    lstat64("/tmp/vulture-test/latest", 0xF8B14F30)    = 0
 6.652732    lstat64("/tmp/vulture-test/latest/current", 0xF8B14F30) = 0
 6.652780    lstat64("/tmp/vulture-test/latest/current/virt", 0xF8B14F30) = 0
 6.652827    lstat64("/tmp/vulture-test/latest/current/virt/lib", 0xF8B14F30) = 0
^C 6.652878    lstat64("/tmp/vulture-test/latest/current/virt/lib/python2.7", 0xF8B14F30) = 0
 6.652929    lstat64("/tmp/vulture-test/latest/current/virt/lib/python2.7/site-packages", 0xF8B14F30) = 0

**Comment by jendrikseipp** [comment]
I ran strace for revisions 7e41b08 and be25c56 on a small (4K loc) project and didn't see much difference regarding the number of open64 and lstat64 calls (I used "strace -c -e open,stat"):

```
Old:

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
  0.00    0.000000           0       814       657 open
  0.00    0.000000           0       661       243 stat
------ ----------- ----------- --------- --------- ----------------
100.00    0.000000                  1475       900 total

New:

% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
100.00    0.000048           0       901       737 open
  0.00    0.000000           0       681       261 stat
------ ----------- ----------- --------- --------- ----------------
100.00    0.000048                  1582       998 total
```

I found this SO answer, https://stackoverflow.com/a/25265904, which might be related. The linked slides are very informative. I don't see how this explains why turning vulture into a package slows down execution  for you though.

I'm not sure what to try next. Do you have an idea? Can you maybe produce a trace for the old version and compare it to the new version? Which additional calls are made?

**Comment by roivanov** [comment]
Attached is truss output for revisions be25c56 and 3787e78 with actual file names replaced with xxx.
You may see that at about line 11900 output starts to differ significantly.
[obf.zip](https://github.com/jendrikseipp/vulture/files/1160032/obf.zip)

The project is django app.

**Comment by jendrikseipp** [comment]
Did I understand correctly that #74 fixes #73 and that the difference of 6s stems from a different slowdown?

**Comment by roivanov** [comment]
Yes, #74 fixes #73.
I can make another run to compare 0.14 vs 0.19 for 6 to 11-12 second change.
Optionally with profiling.

**Comment by jendrikseipp** [comment]
That would be great! It would be nice to know where the slowdown comes from. Profiling (e.g., with "python -m cProfile") might shed some light on this.

**Comment by roivanov** [comment]
Here is the output from python profile commands. Let me know if you need anything else.
Personally, I don't see a big problem of 6s in 0.14 vs 12s in 0.19 since functionality (whitelists) added.

[profile.zip](https://github.com/jendrikseipp/vulture/files/1163472/profile.zip)

**Comment by jendrikseipp** [comment]
Thanks! I have made various changes to speed up vulture. The most important change is probably cfad66ecc99f9d9053ddc3e896262fe7f069a2b2. It would be interesting to know how long it takes to scan your application with the latest git version of vulture.

**Comment by roivanov** [comment]
Wow, impressive, vulture is back to 6 sec.
Before (0.19):
real    0m10.527s
user    0m8.613s
sys     0m1.780s

After (latest clone):
real    0m6.298s
user    0m5.790s
sys     0m0.497s

**Comment by jendrikseipp** [comment]
Nice, thanks for reporting back!
